name: JSR

concurrency:
    group: JSR-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    release:
        types: [created]
    workflow_call:

jobs:
    Publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4.1.1

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org"

            - run: npm install -g npm

            - name: Prepublish .
              continue-on-error: true
              working-directory: .
              run: |
                  npm install --legacy-peer-deps
                  npm run prepublishOnly --legacy-peer-deps

            - name: Install Deno
              uses: denoland/setup-deno@v1.1.4

            - name: Publish package
              run: deno publish
