name: NPM

concurrency:
    group: npm-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write

on:
    workflow_dispatch:
    release:
        types: [created]
    workflow_call:

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v3.5.2
            - uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7.17.1
                  run_install: |
                      - recursive: true
                        args: [
                          --child-concurrency=9999,
                          --link-workspace-packages=true,
                          --lockfile-only,
                          --network-concurrency=9999,
                          --prefer-frozen-lockfile=false,
                          --shamefully-hoist=false,
                          --shared-workspace-lockfile=true,
                          --strict-peer-dependencies=false,
                          --unsafe-perm=true
                        ]
            - uses: actions/setup-node@v3.6.0
              with:
                  node-version: "18"
                  cache: "pnpm"
                  cache-dependency-path: ./pnpm-lock.yaml
                  registry-url: "https://registry.npmjs.org"

            - run: pnpm install
              working-directory: .

            - run: pnpm run build
              working-directory: .

            - run: ls -lha
            - run: ls -lha dist/
            # - run: npm publish --legacy-peer-deps
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
